import random

# sets the questions and answers for the quiz
questions = ["question 1", "question 2", "question 3", "question 4"]
answers = ["answer 1", "answer 2", "answer 3", "answer 4"]
numbers_used = []
valid_num = False


# randomizer function that returns a random question and its answer from the questions and answers lists.
def randomizer():
    while not valid_num:
        # sets a variable (num_of_questions) as the amount of questions in the variable questions - 1
        num_of_questions = len(questions) - 1
        # sets the question number randomly from 0 to the amount of question's in questions - 1
        question_num = random.randint(0, num_of_questions)

        # Checks if the random number selected is in the list of numbers that have already been used
        if question_num not in numbers_used:
            # adds the number selected to the used numbers list so that it can not be used again
            numbers_used.append(question_num)
            # returns the randomly selected question and answer
            return [questions[question_num], answers[question_num]]


x = 4
while x > 0:
    # calls the randomizer function
    random_question_answer = randomizer()
    # prints the random question and answer that was generated by the randomizer function called above
    print(random_question_answer[0])
    print(random_question_answer[1])
    x -= 1
print("out of questions")

